# Generated by Django 2.0.6 on 2019-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCate',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=40, null=True)),
                ('p_id', models.CharField(blank=True, max_length=40, null=True)),
                ('books', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'book_cate',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('bookname', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('press', models.CharField(blank=True, max_length=40, null=True)),
                ('press_time', models.CharField(blank=True, max_length=40, null=True)),
                ('edition', models.CharField(blank=True, max_length=40, null=True)),
                ('print_time', models.CharField(blank=True, max_length=40, null=True)),
                ('impression', models.CharField(blank=True, max_length=40, null=True)),
                ('number', models.CharField(blank=True, max_length=40, null=True)),
                ('pages', models.CharField(blank=True, max_length=40, null=True)),
                ('paper', models.CharField(blank=True, max_length=40, null=True)),
                ('packaging', models.CharField(blank=True, max_length=40, null=True)),
                ('dangdangpric', models.CharField(blank=True, max_length=40, null=True)),
                ('price', models.CharField(blank=True, max_length=40, null=True)),
                ('save', models.CharField(blank=True, max_length=40, null=True)),
                ('cid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('commoditys', models.CharField(blank=True, max_length=40, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('recipients', models.CharField(blank=True, max_length=40, null=True)),
                ('cellphone', models.CharField(blank=True, max_length=40, null=True)),
                ('postcode', models.CharField(blank=True, max_length=40, null=True)),
                ('cid', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('all_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_id', models.CharField(blank=True, max_length=40, null=True)),
                ('location_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('usemame', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 't_user',
            },
        ),
    ]
